### ISSUE TITLE
Could you please provided the paper to Weight Loss?

### ISSUE THREAD

**Issue by fiona-lxd** [bnuwangxun/Deep_Metric#51]
Hi, I want to cite Weight Loss in my paper. Could you please provide its citation?

**Comment by bnu-wangxun** [comment]
@inproceedings{wang2019multi,
title={Multi-Similarity Loss with General Pair Weighting for Deep Metric Learning},
author={Wang, Xun and Han, Xintong and Huang, Weilin and Dong, Dengke and Scott, Matthew R},
booktitle={CVPR},
year={2019}
}

**Comment by fiona-lxd** [comment]
Got it, thank you very much.
